### ISSUE TITLE
v0.9.2 build failed for android target.

### ISSUE THREAD

**Issue by yangkx1024** [RazrFalcon/memmap2-rs#110]
I'm trying to use this lib in Android project, found that after upgrading to v0.9.2, the build broke, here is the log:
```text
error[E0425]: cannot find value `MAP_HUGE_MASK` in crate `libc`
    --> /Users/***/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memmap2-0.9.2/src/unix.rs:33:42
     |
33   | const MAP_HUGE_MASK: libc::c_int = libc::MAP_HUGE_MASK;
     |                                          ^^^^^^^^^^^^^ help: a constant with a similar name exists: `MFD_HUGE_MASK`
     |
    ::: /Users/***/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.147/src/unix/linux_like/android/mod.rs:2142:1
     |
2142 | pub const MFD_HUGE_MASK: ::c_uint = 63;
     | --------------------------------- similarly named constant `MFD_HUGE_MASK` defined here
```

**Comment by RazrFalcon** [comment]
Weird. Android has `MAP_HUGETLB`, but not `MAP_HUGE_MASK`... Will remove it then.

**Comment by RazrFalcon** [comment]
Please try the latest git version.

**Comment by yangkx1024** [comment]
Works, thanks!
